name: dart_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  my_lints:
    path: ../my_lints
  easy_plugin:
    path: ../easy_plugin
  custom_lint: ^0.6.4
