name: easy_plugin
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
